### ISSUE TITLE
Type declaration error in ml-array-standard-deviation

### ISSUE THREAD

**Issue by ajafff** [mljs/array#18]
```
ERROR in node_modules/ml-array-standard-deviation/types.d.ts:21:3 - error TS2309: An export assignment cannot be used in a module with other exported elements.
    
    21   export = arrayStandardDeviation;
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

`ml-array-standard-deviation@1.1.6`
`typescript@4.0.3`

Also reproduces in TypeScript playground with latest stable version: https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEBbA9sArhBByREC0sMUAnngM4AuUAdsLMHqAG4CWUFLy1W8A3gLAAoePBAAPAA7IYFeC2oUQMAGZQwCAIIwixAMpVa9ACIhW7TtQDyEjlzJ8hIkQHoAVK8dP4r+AEll8BQwaCAANPDALKyg8ABGxPAAFNR4AIwAlAB0fgGqEGRhEVEsMfHw1JmeTj4AAqCqGLJBIVUirs6taNSxbAXAAPwAXHHIyJg0ANytbh7CXj4ACnBgUBBgGOwgwEggNJVz1R0HOzRD5WiIsUpTcwC+Qp4zVT4AwsiIEmiK9hQAFgiUGh0GDbZhsWzUeDIAJ-BAAcyiIEhTFWITI+0OnmUXTAEPghBI+iBxlM4IsiVaBOIwy0OgAMiwANYgAA81AuVxgAD5Qq1kDYLGQzrTCQZgcATGYIdYIWReXN0sN2Zdrp5xFIZPAALz47Si4kgyVkrg3e6CIA

The same issue probably also applies to `ml-array-variance`

Proposed fix: wrap the interface declaration in a namespace which has the same name as the exported function:

```ts
declare module 'ml-array-standard-deviation' {
    namespace arrayStandardDeviation {  // <-- here
      export interface ArrayStandardDeviationOptions {
        /**
         * If true, divide by (n-1). If false, divide by n.
         * @default true
         */
        unbiased?: boolean;
        /**
         * Precalculated mean.
         */
        mean?: number;
      }
    }

  /**
   * Computes the standard deviation of the given values.
   */
  function arrayStandardDeviation(
    array: ArrayLike<number>,
    options?: arrayStandardDeviation.ArrayStandardDeviationOptions,
  ): number;
  export = arrayStandardDeviation;
}

```

**Comment by targos** [comment]
Indeed, that's what we did for some of the packages in https://github.com/mljs/array/commit/3b5c7258df898ec5d35af70ac51570f956e1f9a8
Would you like to do a PR?
